version: '3.9'

services:
  chatapp:
    image: ilhamfadhilah/chatapp:dev
    build:
      context: ../../
      dockerfile: ./misc/docker/dockerfile
      target: base
    ports:
      - 8000:8000
    volumes:
      - ../..:/src/app
    command: bash -c "yarn start:dev"
    networks:
      default: