version: '3.9'
services:
  chatapp:
    restart: unless-stopped
  mongodb:
    image: mongo:6.0.1
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - './volumes/mongodb/data:/data/db'
    networks:
      default:
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/

networks:
  default:
